/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;


import org.ini4j.Wini;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import logica.Usuario;
/**
 *
 * @author galax
 */
public class w_new_usuario extends javax.swing.JFrame {

    /**
     * Creates new form w_new_usuario
     */
    public w_new_usuario() {
        initComponents();
        try{
            File archivo = new File("myiniFinal.ini"); 
            Wini ini = new Wini(new File(archivo.getAbsolutePath()));            
            usuarios = ini.get("Archivos", "usuarios");
            
            //tipos_usuarios = ini.get("Archivos", "tiposusuarios");
            
            /*
            Nombresis = ini.get("App", "Nombre");
            Autor = ini.get("App", "Autor");
            Email = ini.get("App", "Email");
            Telefono = ini.get("App", "Telefeno");
            Web = ini.get("App", "Web");
            */            
            
            //mostrarDatos_combo_tipos();
            
        }catch(IOException e){
            System.err.println(e.getMessage());
        } 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ComboBoxTipo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        btnSaveUser = new javax.swing.JButton();
        IdInput = new javax.swing.JTextField();
        UsuarioInput = new javax.swing.JTextField();
        ClaveInput = new javax.swing.JPasswordField();
        txtContra = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JLabel();
        txtId = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "asd 1", "asfboa 2", "spidah 3", "asda 4" }));

        jLabel3.setText("Tipo:");

        btnSaveUser.setText("Registrar");
        btnSaveUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveUserActionPerformed(evt);
            }
        });

        IdInput.setText("Id");

        UsuarioInput.setText("Usuario");

        ClaveInput.setText("jPasswordField1");

        txtContra.setText("Contraseña:");

        txtUsuario.setText("Usuario:");

        txtId.setText("Id");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtContra)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtId, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtUsuario, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(UsuarioInput)
                                .addComponent(ClaveInput)
                                .addComponent(IdInput, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btnSaveUser))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId)
                    .addComponent(IdInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario)
                    .addComponent(UsuarioInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContra)
                    .addComponent(ClaveInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(35, 35, 35)
                .addComponent(btnSaveUser)
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveUserActionPerformed
        this.Agregar_usuario();
        this.GrabarDatos_usuario();
        JOptionPane.showMessageDialog(null, "Nuevo usuario registrado!");
    }//GEN-LAST:event_btnSaveUserActionPerformed
    
    //metodos
    public void Agregar_usuario() {
        Usuario u = new Usuario("", "", "", "");
        u.setId(this.IdInput.getText());
        u.setUsuario(this.UsuarioInput.getText());
        u.setClave(Arrays.toString(this.ClaveInput.getPassword()));
        u.setTipo(this.ComboBoxTipo.getSelectedItem().toString());
        lista_usuarios.add(u);
        JOptionPane.showMessageDialog(null, "Usuario agregado");
    }

    public void GrabarDatos_usuario() {
        try {
            File archivo = new File(usuarios);
            FileOutputStream fos = new FileOutputStream(archivo.getAbsolutePath());
            ObjectOutputStream oos = new ObjectOutputStream(fos);
            oos.writeObject(lista_usuarios);
            oos.close();
        } catch (IOException ex) {
        }
    }

    public void LeerDatos_usuario() {
        try {
            File archivo = new File(usuarios);
            FileInputStream fin = new FileInputStream(archivo.getAbsolutePath());
            ObjectInputStream ois = new ObjectInputStream(fin);
            try {
                lista_usuarios = (ArrayList<Usuario>) ois.readObject();
            } catch (ClassNotFoundException e) {
                System.err.println(e.getMessage());
            }
            fin.close();
        } catch (IOException ex) {
            System.err.println(ex.getMessage());
        }
    }
    
    //variables globales
    String usuarios;
    ArrayList<Usuario> lista_usuarios = new ArrayList<>();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ClaveInput;
    private javax.swing.JComboBox<String> ComboBoxTipo;
    private javax.swing.JTextField IdInput;
    private javax.swing.JTextField UsuarioInput;
    private javax.swing.JButton btnSaveUser;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtContra;
    private javax.swing.JLabel txtId;
    private javax.swing.JLabel txtUsuario;
    // End of variables declaration//GEN-END:variables
}
